#!/usr/bin/env bash
#This script display passwd with ifs

file=/etc/passwd
cont=1

while IFS=: read -r username password userid groupid comment homedir cmdshell
do
echo "The user $username is part of the $groupid gang, lives in $homedir and rides $cmdshell. USER $userid's place is protected by the passcode $password, more info about the user here: $comment" 

cont=$((cont + 1))
done < $file
