#!/usr/bin/env bash
#This script display "bad luck" for the 4th iterations, "good luck" for the 8th iterations and "best school" for the others
cont=1
while [ $cont -lt 11 ]
do
                if [ $cont -eq 4 ]
                then
                        echo "bad luck"
		elif [ $cont -eq 8 ]
		then
			echo "good luck" 
		else
			echo "Best School"
		fi
        cont=$(( cont + 1 ))
done
