#!/usr/bin/env bash
#This script display the time for 12 hours and 59 minutes
cont=0
while [ $cont -lt 13 ]
do
	min=-1
	while [ $min -lt 59 ]
	do
	
		min=$(( min + 1 ))

		if [ $min -eq 0 ]
		then
			echo "Hour: " $cont
		else
			echo $min
		fi
	done
	cont=$(( cont + 1 ))
done
