#!/usr/bin/env bash
#a

echo $$ > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"

	trap "echo I hate the kill command; exit" SIGTERM
	trap "echo Y U no love me?!; exit" SIGINT
	trap "rm /var/run/myscript.pid; exit" SIGQUIT || SIGTERM
done
